const ready = window.SUPABASE_URL && !window.SUPABASE_URL.startsWith('PASTE_');
const message = document.getElementById('loginMessage');
const configNote = document.getElementById('configNote');
let db;
if (ready) { db = window.supabase.createClient(window.SUPABASE_URL, window.SUPABASE_ANON_KEY); configNote.style.display='none'; }
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}
async function listWorks(){if(!db)return;const {data,error}=await db.from('artworks').select('*').order('created_at',{ascending:false});if(error)return;document.getElementById('artList').innerHTML=data.map(w=>`<article><img src="${escapeHtml(w.image_url)}" alt=""><h3>${escapeHtml(w.title)}</h3><p>${escapeHtml(w.status)} · ${escapeHtml(w.year||'')}</p></article>`).join('');}
async function showDashboard(){document.getElementById('login').style.display='none';document.getElementById('dashboard').classList.add('show');listWorks();}
if(ready){db.auth.getSession().then(({data})=>{if(data.session)showDashboard()});}
document.getElementById('loginForm').addEventListener('submit',async e=>{e.preventDefault();if(!ready){message.textContent='Add the Supabase Project URL and anon key first.';return}message.textContent='Signing in…';const {error}=await db.auth.signInWithPassword({email:email.value,password:password.value});if(error){message.textContent=error.message;return}showDashboard();});
document.getElementById('logout').addEventListener('click',async()=>{await db.auth.signOut();location.reload()});
document.getElementById('artForm').addEventListener('submit',async e=>{e.preventDefault();if(!db)return;const out=document.getElementById('formMessage'),file=image.files[0];if(file.size>8*1024*1024){out.textContent='Please use an image under 8 MB.';return}out.textContent='Uploading image…';const ext=file.name.split('.').pop();const path=`${Date.now()}-${crypto.randomUUID()}.${ext}`;const upload=await db.storage.from('artworks').upload(path,file,{cacheControl:'31536000',upsert:false});if(upload.error){out.textContent=upload.error.message;return}const {data:url}=db.storage.from('artworks').getPublicUrl(path);out.textContent='Publishing artwork…';const {error}=await db.from('artworks').insert({title:title.value,category:category.value,medium:medium.value,dimensions:dimensions.value,year:artYear.value,status:status.value,description:description.value,image_url:url.publicUrl});if(error){out.textContent=error.message;return}out.textContent='Published successfully.';e.target.reset();listWorks();});
