import * as THREE from './vendor/three.module.js';
const canvas=document.querySelector('#world'), scene=new THREE.Scene(), camera=new THREE.PerspectiveCamera(46,innerWidth/innerHeight,.1,100), renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));camera.position.set(0,0,10);scene.fog=new THREE.FogExp2(0x090410,.045);
const works=[
 ['Unspoken','Figurative Art — Realism','assets/IMG-20260823-WA0007.jpg','A figurative study exploring introspection, vulnerability, and the quiet weight of emotion.'],
 ['Quiet Strength','Wildlife & Animal Portrait','assets/IMG-20260823-WA0005.jpg','A detailed charcoal and graphite study of an elephant: power that needs no display.'],
 ['Untamed','Wildlife & Animal Portrait','assets/IMG-20260823-WA0006.jpg','A study of the tiger in motion—instinct, texture, and unapologetic wildness.'],
 ['Coiled Silence','Wildlife Study','assets/IMG-20260823-WA0012.jpg','A close study of a snake at rest, exploring alert stillness and intricate texture.'],
 ['In Focus','Portrait Realism','assets/IMG-20260823-WA0011.jpg','A direct portrait study shaped through controlled light, deep charcoal, and observation.'],
 ['In Thought','Portrait Realism','assets/IMG-20260823-WA0009.jpg','A graphite and charcoal portrait study of Albert Einstein: curiosity, reflection, and character.']
];
const loader=new THREE.TextureLoader(), frames=[], ray=new THREE.Raycaster(), mouse=new THREE.Vector2();
const violet=new THREE.PointLight(0xc15cff,13,38);violet.position.set(0,2,7);scene.add(violet);const blue=new THREE.PointLight(0x32dfff,9,32);blue.position.set(-5,-1,-8);scene.add(blue);const pink=new THREE.PointLight(0xff4fd8,8,26);pink.position.set(5,3,-16);scene.add(pink);scene.add(new THREE.AmbientLight(0x9165d1,1.25));
function wire(a,b){const g=new THREE.BufferGeometry().setFromPoints([a,b]);const l=new THREE.Line(g,new THREE.LineBasicMaterial({color:0xae63f1,transparent:true,opacity:.45}));scene.add(l)}
function px(i){return i===0?0:(i%2?2.9:-2.9)}
function py(i){return i===0?0:((i%3-1)*.65)}
works.forEach((w,i)=>{const z=-i*8, x=px(i), y=py(i);const group=new THREE.Group();group.position.set(x,y,z);group.rotation.set(0,(i%2?-.22:.22),i%2?-.08:.08);const geo=new THREE.BoxGeometry(4.3,5.5,.18);const mat=new THREE.MeshStandardMaterial({color:0x3b1257,metalness:.8,roughness:.22,emissive:0x180629,emissiveIntensity:.6});const frame=new THREE.Mesh(geo,mat);group.add(frame);const tex=loader.load(w[2]);tex.colorSpace=THREE.SRGBColorSpace;const image=new THREE.Mesh(new THREE.PlaneGeometry(3.82,5.02),new THREE.MeshBasicMaterial({map:tex}));image.position.z=.105;group.add(image);const halo=new THREE.Mesh(new THREE.PlaneGeometry(5.5,6.7),new THREE.MeshBasicMaterial({color:0x9e45e8,transparent:true,opacity:.08,blending:THREE.AdditiveBlending}));halo.position.z=-.13;group.add(halo);group.userData={i,baseY:y,baseRot:group.rotation.y};scene.add(group);frames.push(group);if(i)wire(new THREE.Vector3(px(i),y,z),new THREE.Vector3(px(i-1),py(i-1),z+8));});
const points=new THREE.BufferGeometry(),pos=[];for(let i=0;i<700;i++){pos.push((Math.random()-.5)*25,(Math.random()-.5)*15,-Math.random()*55+5)}points.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));scene.add(new THREE.Points(points,new THREE.PointsMaterial({color:0xd5a7ff,size:.027,transparent:true,opacity:.9})));
let travel=0,target=0,px=0,py=0;addEventListener('scroll',()=>{const max=Math.max(1,document.documentElement.scrollHeight-innerHeight);target=(scrollY/max)*(works.length-1)},{passive:true});addEventListener('wheel',e=>{target=THREE.MathUtils.clamp(target+e.deltaY*.014,0,works.length-1)} ,{passive:true});let startY;addEventListener('touchstart',e=>startY=e.touches[0].clientY,{passive:true});addEventListener('touchmove',e=>{target=THREE.MathUtils.clamp(target+(startY-e.touches[0].clientY)*.012,0,works.length-1);startY=e.touches[0].clientY},{passive:true});addEventListener('pointermove',e=>{px=(e.clientX/innerWidth-.5);py=(e.clientY/innerHeight-.5)});
const detail=document.querySelector('#artDetail');function openWork(i){let w=works[i];detail.querySelector('#detailCat').textContent=w[1];detail.querySelector('#detailTitle').textContent=w[0];detail.querySelector('#detailText').textContent=w[3];detail.querySelector('#enquire').href='https://wa.me/919134499623?text='+encodeURIComponent('Hello Nandini, I am interested in “'+w[0]+'”. Please share availability and delivery details.');detail.classList.add('show')}canvas.addEventListener('click',()=>{ray.setFromCamera(mouse,camera);let hits=ray.intersectObjects(frames,true);if(hits.length){let p=hits[0].object.parent;while(p&&p.userData.i===undefined&&p.parent)p=p.parent;openWork(p.userData.i)}});addEventListener('pointermove',e=>{mouse.x=e.clientX/innerWidth*2-1;mouse.y=-(e.clientY/innerHeight)*2+1});document.querySelectorAll('.close').forEach(x=>x.onclick=()=>{detail.classList.remove('show');document.querySelector('#panel').classList.remove('show')});
const content={about:['THE ARTIST','Nandini Patel','Nandini is a graphite and charcoal artist from India. Her work explores realism, emotion, and quiet human presence through patient observation, texture, and shadow.\n\nCreating quietly, capturing deeply—where silence finds its form.'],commission:['CUSTOM ARTWORK','Commission a story.','Share a photograph, memory, or concept. We will discuss size, timeline, and delivery directly. A 50% advance confirms a commission. Delivery charge: ₹150. Payments are non-refundable once work begins.']};document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>{let d=content[b.dataset.panel],p=document.querySelector('#panel');p.querySelector('#panelKicker').textContent=d[0];p.querySelector('#panelTitle').textContent=d[1];p.querySelector('#panelContent').innerHTML='<p>'+d[2].replaceAll('\n','<br>')+'</p>'+ (b.dataset.panel==='commission'?'<a href="https://wa.me/919134499623">START ON WHATSAPP ↗</a>':'');p.classList.add('show')});
function haloPulse(g,t,i){g.children[2].material.opacity=.055+Math.sin(t*.001+i)*.035}
function render(t){requestAnimationFrame(render);travel=THREE.MathUtils.lerp(travel,target,.035);camera.position.z=10-travel*8;camera.position.x=px*.45;camera.position.y=-py*.32;camera.lookAt(0,0,camera.position.z-6);frames.forEach((g,i)=>{g.position.y=g.userData.baseY+Math.sin(t*.00065+i*1.7)*.19; haloPulse(g,t,i);g.rotation.y=g.userData.baseRot+Math.sin(t*.00045+i)*.12;g.rotation.z=Math.sin(t*.00037+i)*.035});let n=Math.round(travel);document.querySelector('#workNo').textContent=String(n+1).padStart(2,'0');document.querySelector('#workName').textContent=works[n][0].toUpperCase();renderer.render(scene,camera)}render(0);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
